200.what-s-new=What's New
300.odc-overview=产品简介
400.quickstart=快速入门
500.tutorials=教程
600.web-odc-user-guide=用户指南（Web 版 ODC）
100.log-on-to-odc=登录 ODC
1000.web-odc-database-objects=数据库对象
100.web-odc-table-objects=表对象
200.web-odc-view-objects=视图对象
300.web-odc-function-objects=函数对象
400.web-odc-stored-procedure-objects=存储过程对象
500.web-odc-sequence-objects=序列对象
600.web-odc-package-objects=程序包对象
700.web-odc-trigger-objects=触发器对象
800.web-odc-type-objects=类型对象
900.web-odc-synonym-objects=同义词对象
300.web-odc-connect-database=连接数据库
400.web-odc-public-resource-management=公共资源管理
200.web-odc-manage-members=成员管理
300.web-odc-resource-management=资源管理
500.web-odc-use-workspace=使用工作台
600.web-odc-use-tools=使用工具
100.web-odc-data-export-and-import=数据导出和导入
800.web-odc-task-management=任务管理
700.client-odc-user-guide=用户指南（客户端版 ODC）
300.client-odc-connect-database=连接数据库
400.client-odc-use-workspace=使用工作台
500.client-odc-use-tools=使用工具
100.client-odc-data-export-and-import=数据导出和导入
700.client-odc-task-management=任务管理
900.client-odc-database-objects=数据库对象
100.client-odc-table-objects=表对象
200.client-odc-view-objects=视图对象
300.client-odc-function-objects=函数对象
400.client-odc-stored-procedure-objects=存储过程对象
500.client-odc-sequence-objects=序列对象
600.client-odc-package-objects=程序包对象
700.client-odc-trigger-objects=触发器对象
800.client-odc-type-objects=类型对象
900.client-odc-synonym-objects=同义词对象
800.deployment-guide=部署指南
300.deploy-a-single-odc-node=部署单节点 ODC
400.deploy-the-ha-odc=部署高可用 ODC
900.upgrade-guide=升级指南
300.upgrade-single-node-odc=升级单节点 ODC
400.upgrade-high-availability-odc=升级高可用 ODC
