200.what-s-new=What's New
300.odc-overview=Overview
400.quickstart=Quick Start
500.tutorials=Tutorials
600.web-odc-user-guide=User Guide (Web ODC)
100.log-on-to-odc=Log on to ODC
1000.web-odc-database-objects=Database objects
100.web-odc-table-objects=Table objects
200.web-odc-view-objects=View objects
300.web-odc-function-objects=Function objects
400.web-odc-stored-procedure-objects=Stored procedure objects
500.web-odc-sequence-objects=Sequence objects
600.web-odc-package-objects=Package objects
700.web-odc-trigger-objects=Trigger objects
800.web-odc-type-objects=Type objects
900.web-odc-synonym-objects=Synonym objects
300.web-odc-connect-database=Connect to a database
400.web-odc-public-resource-management=Public resource management
200.web-odc-manage-members=Member management
300.web-odc-resource-management=Resource management
500.web-odc-use-workspace=Use the workspace
600.web-odc-use-tools=Use tools
100.web-odc-data-export-and-import=Data export and import
800.web-odc-task-management=Task management
700.client-odc-user-guide=User Guide (Client ODC)
300.client-odc-connect-database=Connect to a database
400.client-odc-use-workspace=Use the workspace
500.client-odc-use-tools=Use tools
100.client-odc-data-export-and-import=Data export and import
700.client-odc-task-management=Task management
900.client-odc-database-objects=Database objects
100.client-odc-table-objects=Table objects
200.client-odc-view-objects=View objects
300.client-odc-function-objects=Function objects
400.client-odc-stored-procedure-objects=Stored procedure objects
500.client-odc-sequence-objects=Sequence objects
600.client-odc-package-objects=Package objects
700.client-odc-trigger-objects=Trigger objects
800.client-odc-type-objects=Type objects
900.client-odc-synonym-objects=Synonym objects
800.deployment-guide=Deployment Guide
300.deploy-a-single-odc-node=Deploy a single ODC node
400.deploy-the-ha-odc=Deploy ODC in high availability mode
900.upgrade-guide=Upgrade Guide
300.upgrade-single-node-odc=Upgrade single-node ODC
400.upgrade-high-availability-odc=Upgrade high-availability
