200.odc-overview=Overview
300.quickstart=Quick Start
100.client-odc-quickstart=Client ODC
200.web-odc-quickstart=Web ODC
400.connection-management=Data Source Management
300.database-operation-and-maintenance=Database O&M
500.sql-development=SQL Development
700.database-objects=Database objects
100.web-odc-table-objects=Table objects
200.web-odc-view-objects=View objects
300.web-odc-function-objects=Function objects
400.web-odc-stored-procedure-objects=Stored procedure objects
500.web-odc-sequence-objects=Sequence objects
600.web-odc-package-objects=Package objects
700.web-odc-trigger-objects=Trigger objects
800.web-odc-type-objects=Type objects
900.web-odc-synonym-objects=Synonym objects
600.import-and-export=Import and Export
700.database-change-management=Database Change Management
100.user-permission-and-management=User Permission Management
800.data-Lifecycle-management=Data Lifecycle Management
300.partition-scheme-management=Partitioning Plan Management
900.data-security-and-compliance=Data Desensitization and Auditing
1000.system-integration=System Integration
1100.deployment-guide=Deployment Guide
300.deploy-a-single-odc-node=Deploy a single ODC node
400.deploy-the-ha-odc=Deploy ODC in high availability mode
1200.upgrade-guide=Upgrade Guide
300.upgrade-single-node-odc=Upgrade single-node ODC
400.upgrade-high-availability-odc=Upgrade high-availability
1300.troubleshooting=Troubleshooting
200.collect-message=Collect Message
300.common-troubleshooting=Common Troubleshooting
100.deployment-upgrade=Deployment Upgrade
200.database-connection=Database Connection
300.sql-execution=SQL Execution
400.pl-object=PL Object
500.import-and-export=Import and Export
600.client-odc-problems=Client ODC Problems
700.front-page-exception=Front-end Page Exception
800.account-password-problem=Account Password Problem
400.faq=FAQ
1400.odc-rn=Release Note
90.odc-rn-4.2=V4.2
100.odc-rn-4.1=V4.1
200.odc-rn-4.0=V4.0
300.odc-rn-3.4=V3.4
400.odc-rn-3.3=V3.3
500.odc-rn-3.2=V3.2