200.odc-overview=产品简介
300.quickstart=快速入门
100.client-odc-quickstart=桌面版 ODC
200.web-odc-quickstart=Web 版 ODC
400.connection-management=数据源管理
300.database-operation-and-maintenance=数据库运维
500.sql-development=SQL 开发
700.database-objects=数据库对象
100.web-odc-table-objects=表对象
200.web-odc-view-objects=视图对象
300.web-odc-function-objects=函数对象
400.web-odc-stored-procedure-objects=存储过程对象
500.web-odc-sequence-objects=序列对象
600.web-odc-package-objects=程序包对象
700.web-odc-trigger-objects=触发器对象
800.web-odc-type-objects=类型对象
900.web-odc-synonym-objects=同义词对象
600.import-and-export=导入和导出
700.database-change-management=变更风险管控
100.user-permission-and-management=用户权限管理
800.data-Lifecycle-management=数据生命周期管理
900.data-security-and-compliance=数据脱敏与审计
1000.system-integration=系统集成
400.bastion-host-integration-guide=堡垒机集成
1100.deployment-guide=部署指南
1200.upgrade-guide=升级指南
1300.troubleshooting=故障排查
200.collect-message=信息收集
300.common-troubleshooting=常见故障
100.deployment-upgrade=部署升级
200.database-connection=数据库连接
300.sql-execution=SQL 执行
400.pl-object=PL 对象
500.import-and-export=导入和导出
600.client-odc-problems=桌面版问题
700.front-page-exception=前端页面异常
800.account-password-problem=账号密码问题
400.faq=常见问题
1400.rn=版本发布记录
100.odc-rn-4.2=V4.2
200.odc-rn-4.1=V4.1
300.odc-rn-4.0=V4.0
400.odc-rn-3.4=V3.4
500.odc-rn-3.3=V3.3
600.odc-rn-3.2=V3.2
