2.what-s-new=What's New
3.odc-overview=产品简介
4.quickstart=快速入门
5.tutorials=教程
6.web-odc-user-guide=用户指南（Web 版 ODC）
1.log-on-to-odc=登录 ODC
11.web-odc-database-objects=数据库对象
1.web-odc-table-objects=表对象
2.web-odc-view-objects=视图对象
3.web-odc-function-objects=函数对象
4.web-odc-stored-procedure-objects=存储过程对象
5.web-odc-sequence-objects=序列对象
6.web-odc-package-objects=程序包对象
7.web-odc-trigger-objects=触发器对象
8.web-odc-type-objects=类型对象
9.web-odc-synonym-objects=同义词对象
3.web-odc-connect-database=连接数据库
4.web-odc-public-resource-management=公共资源管理
3.web-odc-public-resource-permission=资源权限
5.web-odc-use-workspace=使用工作台
6.web-odc-use-tools=使用工具
1.web-odc-data-export-and-import=数据导出和导入
9.web-odc-task-management=任务管理
7.client-odc-user-guide=用户指南（客户端版 ODC）
10.client-odc-database-objects=数据库对象
1.client-odc-table-objects=表对象
2.client-odc-view-objects=视图对象
3.client-odc-function-objects=函数对象
4.client-odc-stored-procedure-objects=存储过程对象
5.client-odc-sequence-objects=序列对象
6.client-odc-package-objects=程序包对象
7.client-odc-trigger-objects=触发器对象
8.client-odc-type-objects=类型对象
9.client-odc-synonym-objects=同义词对象
3.client-odc-connect-database=连接数据库
4.client-odc-use-workspace=使用工作台
5.client-odc-use-tools=使用工具
1.client-odc-data-export-and-import=数据导出和导入
8.client-odc-task-management=任务管理
8.deployment-guide=部署指南
3.deploy-a-single-odc-node=部署单节点 ODC
4.deploy-the-ha-odc=部署高可用 ODC
9.upgrade-guide=升级指南
3.upgrade-single-node-odc=升级单节点 ODC
4.upgrade-high-availability-odc=升级高可用 ODC
10.bastion-host-integration-guide=堡垒机集成参考