2.odc-overview=产品简介
3.quickstart=快速入门
1.client-odc-quickstart=桌面版 ODC
2.web-odc-quickstart=Web 版 ODC
4.connection-management=数据源管理
3.database-operation-and-maintenance=数据库运维
5.sql-development=SQL 开发
7.database-objects=数据库对象
1.web-odc-table-objects=表对象
2.web-odc-view-objects=视图对象
3.web-odc-function-objects=函数对象
4.web-odc-stored-procedure-objects=存储过程对象
5.web-odc-sequence-objects=序列对象
6.web-odc-package-objects=程序包对象
7.web-odc-trigger-objects=触发器对象
8.web-odc-type-objects=类型对象
9.web-odc-synonym-objects=同义词对象
6.import-and-export=导入和导出
7.database-change-management=变更风险管控
1.user-permission-and-management=用户权限管理
8.data-Lifecycle-management=数据生命周期管理
9.data-security-and-compliance=数据脱敏与审计
10.system-integration=系统集成
4.bastion-host-integration-guide=堡垒机集成
11.deployment-guide=部署指南
3.deploy-a-single-odc-node=部署单节点 ODC
4.deploy-the-ha-odc=部署高可用 ODC
12.upgrade-guide=升级指南
3.upgrade-single-node-odc=升级单节点 ODC
4.upgrade-high-availability-odc=升级高可用 ODC
13.troubleshooting=故障排查
2.collect-message=信息收集
3.common-troubleshooting=常见故障
1.deployment-upgrade=部署升级
2.database-connection=数据库连接
3.sql-execution=SQL 执行
4.pl-object=PL 对象
5.import-and-export=导入和导出
6.client-odc-problems=桌面版问题
7.front-page-exception=前端页面异常
8.account-password-problem=账号密码问题
4.faq=常见问题
14.rn=版本发布记录
1.odc-rn-4.2=V4.2
2.odc-rn-4.1=V4.1
3.odc-rn-4.0=V4.0
4.odc-rn-3.4=V3.4
5.odc-rn-3.3=V3.3
6.odc-rn-3.2=V3.2